//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.AEGIS.Storage.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ELTE.AEGIS.Storage.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication is null..
        /// </summary>
        internal static string AuthenticationIsNull {
            get {
                return ResourceManager.GetString("AuthenticationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is null..
        /// </summary>
        internal static string ClientIsNull {
            get {
                return ResourceManager.GetString("ClientIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path already exists..
        /// </summary>
        internal static string DestinationPathExists {
            get {
                return ResourceManager.GetString("DestinationPathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path is empty, or consists only of whitespace characters..
        /// </summary>
        internal static string DestinationPathIsEmpty {
            get {
                return ResourceManager.GetString("DestinationPathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path is null..
        /// </summary>
        internal static string DestinationPathIsNull {
            get {
                return ResourceManager.GetString("DestinationPathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname is empty, or consists only of whitespace characters..
        /// </summary>
        internal static string HostnameIsEmpty {
            get {
                return ResourceManager.GetString("HostnameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname is in an invalid format..
        /// </summary>
        internal static string HostnameIsInvalid {
            get {
                return ResourceManager.GetString("HostnameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname is null..
        /// </summary>
        internal static string HostnameIsNull {
            get {
                return ResourceManager.GetString("HostnameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote address returned with an invalid response..
        /// </summary>
        internal static string InvalidResponseFromRemote {
            get {
                return ResourceManager.GetString("InvalidResponseFromRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search pattern is an invalid format..
        /// </summary>
        internal static string InvalidSearchPattern {
            get {
                return ResourceManager.GetString("InvalidSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length is less than 0..
        /// </summary>
        internal static string LengthIsLessThan0 {
            get {
                return ResourceManager.GetString("LengthIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is null..
        /// </summary>
        internal static string LocationIsNull {
            get {
                return ResourceManager.GetString("LocationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection is available to the file system..
        /// </summary>
        internal static string NoConnectionToFileSystem {
            get {
                return ResourceManager.GetString("NoConnectionToFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection is available to the specified path..
        /// </summary>
        internal static string NoConnectionToPath {
            get {
                return ResourceManager.GetString("NoConnectionToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset is less than 0..
        /// </summary>
        internal static string OffsetIsLessThan0 {
            get {
                return ResourceManager.GetString("OffsetIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not supported by the file system..
        /// </summary>
        internal static string OperationNotSupported {
            get {
                return ResourceManager.GetString("OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is empty, or consists only of whitespace characters..
        /// </summary>
        internal static string PathIsEmpty {
            get {
                return ResourceManager.GetString("PathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is in an invalid format..
        /// </summary>
        internal static string PathIsInInvalidFormat {
            get {
                return ResourceManager.GetString("PathIsInInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is null..
        /// </summary>
        internal static string PathIsNull {
            get {
                return ResourceManager.GetString("PathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path does not exist..
        /// </summary>
        internal static string PathNotExists {
            get {
                return ResourceManager.GetString("PathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller does not have the required permission for the path..
        /// </summary>
        internal static string PathUnauthorized {
            get {
                return ResourceManager.GetString("PathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port number is less than 1..
        /// </summary>
        internal static string PostNumberIsLessThan1 {
            get {
                return ResourceManager.GetString("PostNumberIsLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and destination paths are equal..
        /// </summary>
        internal static string SourceDestinationPathEqual {
            get {
                return ResourceManager.GetString("SourceDestinationPathEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path is empty, or consists only of whitespace characters..
        /// </summary>
        internal static string SourcePathIsEmpty {
            get {
                return ResourceManager.GetString("SourcePathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path is null..
        /// </summary>
        internal static string SourcePathIsNull {
            get {
                return ResourceManager.GetString("SourcePathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is empty..
        /// </summary>
        internal static string UsernameIsEmpty {
            get {
                return ResourceManager.GetString("UsernameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is null..
        /// </summary>
        internal static string UsernameIsNull {
            get {
                return ResourceManager.GetString("UsernameIsNull", resourceCulture);
            }
        }
    }
}
