//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEGIS.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AEGIS.Resources.CoreMessages", typeof(CoreMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute collection is null..
        /// </summary>
        public static string AttributeCollectionIsNull {
            get {
                return ResourceManager.GetString("AttributeCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute factory is null..
        /// </summary>
        public static string AttributeFactoryIsNull {
            get {
                return ResourceManager.GetString("AttributeFactoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer is null..
        /// </summary>
        public static string BufferIsNull {
            get {
                return ResourceManager.GetString("BufferIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipping window is null..
        /// </summary>
        public static string ClippingWindowIsNull {
            get {
                return ResourceManager.GetString("ClippingWindowIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains one or more duplicate identifiers..
        /// </summary>
        public static string CollectionContainsDuplicateIdentifiers {
            get {
                return ResourceManager.GetString("CollectionContainsDuplicateIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is null..
        /// </summary>
        public static string CollectionIsNull {
            get {
                return ResourceManager.GetString("CollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The convexity ratio is greater than 1..
        /// </summary>
        public static string ConvexityRatioGreaterThan1 {
            get {
                return ResourceManager.GetString("ConvexityRatioGreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The convexity ratio is less than 0..
        /// </summary>
        public static string ConvexityRatioLessThan0 {
            get {
                return ResourceManager.GetString("ConvexityRatioLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of coordinates is less than 3..
        /// </summary>
        public static string CoordinateCountLessThan3 {
            get {
                return ResourceManager.GetString("CoordinateCountLessThan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate is null..
        /// </summary>
        public static string CoordinateIsNull {
            get {
                return ResourceManager.GetString("CoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of coordinates is null..
        /// </summary>
        public static string CoordinatesArrayIsNull {
            get {
                return ResourceManager.GetString("CoordinatesArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of coordinates is null..
        /// </summary>
        public static string CoordinatesCollectionIsNull {
            get {
                return ResourceManager.GetString("CoordinatesCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delta is less than or equal to 0..
        /// </summary>
        public static string DeltaIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("DeltaIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension is greater than 3..
        /// </summary>
        public static string DimensionIsGreaterThan3 {
            get {
                return ResourceManager.GetString("DimensionIsGreaterThan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified dimension is invalid..
        /// </summary>
        public static string DimensionIsInvalid {
            get {
                return ResourceManager.GetString("DimensionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension is less than 2..
        /// </summary>
        public static string DimensionIsLessThan2 {
            get {
                return ResourceManager.GetString("DimensionIsLessThan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end point is null..
        /// </summary>
        public static string EndPointIsNull {
            get {
                return ResourceManager.GetString("EndPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The envelope is null..
        /// </summary>
        public static string EnvelopeIsNull {
            get {
                return ResourceManager.GetString("EnvelopeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The envelope&apos;s minimum coordinate is greater than the maximum coordinate..
        /// </summary>
        public static string EnvelopeMinIsGreaterThanMax {
            get {
                return ResourceManager.GetString("EnvelopeMinIsGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge of the event is greater than the number of edges in the source..
        /// </summary>
        public static string EventEdgeIsGreaterThanNumberOfEdges {
            get {
                return ResourceManager.GetString("EventEdgeIsGreaterThanNumberOfEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge of the event is less than 0..
        /// </summary>
        public static string EventEdgeIsLessThan0 {
            get {
                return ResourceManager.GetString("EventEdgeIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event is null..
        /// </summary>
        public static string EventIsNull {
            get {
                return ResourceManager.GetString("EventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory behavior is null..
        /// </summary>
        public static string FactoryBehaviorIsNull {
            get {
                return ResourceManager.GetString("FactoryBehaviorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory contact is null..
        /// </summary>
        public static string FactoryContractIsNull {
            get {
                return ResourceManager.GetString("FactoryContractIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory is invalid..
        /// </summary>
        public static string FactoryIsInvalid {
            get {
                return ResourceManager.GetString("FactoryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory is null..
        /// </summary>
        public static string FactoryIsNull {
            get {
                return ResourceManager.GetString("FactoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory behavior does not implement the contract..
        /// </summary>
        public static string FactoryNotImplementingContract {
            get {
                return ResourceManager.GetString("FactoryNotImplementingContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature collection is null..
        /// </summary>
        public static string FeatureCollectionIsNull {
            get {
                return ResourceManager.GetString("FeatureCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is null..
        /// </summary>
        public static string FeatureIsNull {
            get {
                return ResourceManager.GetString("FeatureIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first collection is null..
        /// </summary>
        public static string FirstCollectionIsNull {
            get {
                return ResourceManager.GetString("FirstCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first coordinate is null..
        /// </summary>
        public static string FirstCoordinateIsNull {
            get {
                return ResourceManager.GetString("FirstCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first geometry is null..
        /// </summary>
        public static string FirstGeometryIsNull {
            get {
                return ResourceManager.GetString("FirstGeometryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first line string is null..
        /// </summary>
        public static string FirstLineStringIsNull {
            get {
                return ResourceManager.GetString("FirstLineStringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first point is null..
        /// </summary>
        public static string FirstPointIsNull {
            get {
                return ResourceManager.GetString("FirstPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first polygon is null..
        /// </summary>
        public static string FirstPolygonIsNull {
            get {
                return ResourceManager.GetString("FirstPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first vector is null..
        /// </summary>
        public static string FirstVectorIsNull {
            get {
                return ResourceManager.GetString("FirstVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison of the specified geometries is not supported..
        /// </summary>
        public static string GeometryComparisonNotSupported {
            get {
                return ResourceManager.GetString("GeometryComparisonNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry factory is null..
        /// </summary>
        public static string GeometryFactoryIsNull {
            get {
                return ResourceManager.GetString("GeometryFactoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified geometry is invalid..
        /// </summary>
        public static string GeometryIsInvalid {
            get {
                return ResourceManager.GetString("GeometryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified geometry is not supported..
        /// </summary>
        public static string GeometryIsNotSupported {
            get {
                return ResourceManager.GetString("GeometryIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry is null..
        /// </summary>
        public static string GeometryIsNull {
            get {
                return ResourceManager.GetString("GeometryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the geometry is not supported..
        /// </summary>
        public static string GeometryTypeNotSupported {
            get {
                return ResourceManager.GetString("GeometryTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hole is null..
        /// </summary>
        public static string HoleIsNull {
            get {
                return ResourceManager.GetString("HoleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holes are not supported in the triangle..
        /// </summary>
        public static string HolesNotSupportedInTriangle {
            get {
                return ResourceManager.GetString("HolesNotSupportedInTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier is null..
        /// </summary>
        public static string IdentifierIsNull {
            get {
                return ResourceManager.GetString("IdentifierIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is equal to or greater than the number of holes..
        /// </summary>
        public static string IndexIsEqualToOrGreaterThanHoleCount {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanHoleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the number of coordinates..
        /// </summary>
        public static string IndexIsEqualToOrGreaterThanNumberOfCoordinates {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanNumberOfCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is less than 0..
        /// </summary>
        public static string IndexIsLessThan0 {
            get {
                return ResourceManager.GetString("IndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intersection event is null..
        /// </summary>
        public static string IntersectionEventIsNull {
            get {
                return ResourceManager.GetString("IntersectionEventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same identifier already exists in the collection..
        /// </summary>
        public static string ItemIdentifierExists {
            get {
                return ResourceManager.GetString("ItemIdentifierExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is null..
        /// </summary>
        public static string ItemIsNull {
            get {
                return ResourceManager.GetString("ItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension of lines is not supported..
        /// </summary>
        public static string LineExtensionNotSupported {
            get {
                return ResourceManager.GetString("LineExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduction of lines is not supported..
        /// </summary>
        public static string LineReductionNotSupported {
            get {
                return ResourceManager.GetString("LineReductionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line string is null..
        /// </summary>
        public static string LineStringIsNull {
            get {
                return ResourceManager.GetString("LineStringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of child nodes is equal to or less than the minimum number of child nodes..
        /// </summary>
        public static string MaximumNumberOfChildNodesIsEqualToMinimum {
            get {
                return ResourceManager.GetString("MaximumNumberOfChildNodesIsEqualToMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of child nodes is less than 1..
        /// </summary>
        public static string MinimumNumberOfChildNodesIsLessThan1 {
            get {
                return ResourceManager.GetString("MinimumNumberOfChildNodesIsLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of models is null..
        /// </summary>
        public static string ModelsArrayIsNull {
            get {
                return ResourceManager.GetString("ModelsArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no holes in the polygon..
        /// </summary>
        public static string NoHolesInPolygon {
            get {
                return ResourceManager.GetString("NoHolesInPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No models are specified..
        /// </summary>
        public static string NoModelsSpecified {
            get {
                return ResourceManager.GetString("NoModelsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of coordinates is less than 3..
        /// </summary>
        public static string NumberOfCoordinatesIsLessThan3 {
            get {
                return ResourceManager.GetString("NumberOfCoordinatesIsLessThan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin is null..
        /// </summary>
        public static string OriginIsNull {
            get {
                return ResourceManager.GetString("OriginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other feature is null..
        /// </summary>
        public static string OtherFeatureIsNull {
            get {
                return ResourceManager.GetString("OtherFeatureIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other geometry collection is null..
        /// </summary>
        public static string OtherGeometryCollectionIsNull {
            get {
                return ResourceManager.GetString("OtherGeometryCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other geometry is null..
        /// </summary>
        public static string OtherGeometryIsNull {
            get {
                return ResourceManager.GetString("OtherGeometryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the other geometry is not supported..
        /// </summary>
        public static string OtherGeometryNotSupported {
            get {
                return ResourceManager.GetString("OtherGeometryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other linear ring is null..
        /// </summary>
        public static string OtherLinearRingIsNull {
            get {
                return ResourceManager.GetString("OtherLinearRingIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other line is null..
        /// </summary>
        public static string OtherLineIsNull {
            get {
                return ResourceManager.GetString("OtherLineIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other line string is null..
        /// </summary>
        public static string OtherLineStringIsNull {
            get {
                return ResourceManager.GetString("OtherLineStringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other multi line string is null..
        /// </summary>
        public static string OtherMultiLineStringIsNull {
            get {
                return ResourceManager.GetString("OtherMultiLineStringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other multi point is null..
        /// </summary>
        public static string OtherMultiPointIsNull {
            get {
                return ResourceManager.GetString("OtherMultiPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other multi polygon is null..
        /// </summary>
        public static string OtherMultiPolygonIsNull {
            get {
                return ResourceManager.GetString("OtherMultiPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other point is null..
        /// </summary>
        public static string OtherPointIsNull {
            get {
                return ResourceManager.GetString("OtherPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other polygon is null..
        /// </summary>
        public static string OtherPolygonIsNull {
            get {
                return ResourceManager.GetString("OtherPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other triangle is null..
        /// </summary>
        public static string OtherTriangleIsNull {
            get {
                return ResourceManager.GetString("OtherTriangleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point is null..
        /// </summary>
        public static string PointIsNull {
            get {
                return ResourceManager.GetString("PointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polygon is null..
        /// </summary>
        public static string PolygonIsNull {
            get {
                return ResourceManager.GetString("PolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference system factory is null..
        /// </summary>
        public static string ReferenceSystemFactoryIsNull {
            get {
                return ResourceManager.GetString("ReferenceSystemFactoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is equal to or less than 0..
        /// </summary>
        public static string ScaleIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("ScaleIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second collection is null..
        /// </summary>
        public static string SecondCollectionIsNull {
            get {
                return ResourceManager.GetString("SecondCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second Coordinate is null..
        /// </summary>
        public static string SecondCoordinateIsNull {
            get {
                return ResourceManager.GetString("SecondCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second geometry is null..
        /// </summary>
        public static string SecondGeometryIsNull {
            get {
                return ResourceManager.GetString("SecondGeometryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second line string is null..
        /// </summary>
        public static string SecondLineStringIsNull {
            get {
                return ResourceManager.GetString("SecondLineStringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second point is null..
        /// </summary>
        public static string SecondPointIsNull {
            get {
                return ResourceManager.GetString("SecondPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second polygon is null..
        /// </summary>
        public static string SecondPolygonIsNull {
            get {
                return ResourceManager.GetString("SecondPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second vector is null..
        /// </summary>
        public static string SecondVectorIsNull {
            get {
                return ResourceManager.GetString("SecondVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segment is null..
        /// </summary>
        public static string SegmentIsNull {
            get {
                return ResourceManager.GetString("SegmentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segments do not intersect..
        /// </summary>
        public static string SegmentsDoNotIntersect {
            get {
                return ResourceManager.GetString("SegmentsDoNotIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segments do not overlap..
        /// </summary>
        public static string SegmentsDoNotOverlap {
            get {
                return ResourceManager.GetString("SegmentsDoNotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shell is null..
        /// </summary>
        public static string ShellIsNull {
            get {
                return ResourceManager.GetString("ShellIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source is invalid..
        /// </summary>
        public static string SourceIsInvalid {
            get {
                return ResourceManager.GetString("SourceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source is not supported..
        /// </summary>
        public static string SourceIsNotSupported {
            get {
                return ResourceManager.GetString("SourceIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source is null..
        /// </summary>
        public static string SourceIsNull {
            get {
                return ResourceManager.GetString("SourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start point is null..
        /// </summary>
        public static string StartPointIsNull {
            get {
                return ResourceManager.GetString("StartPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The third point is null..
        /// </summary>
        public static string ThirdPointIsNull {
            get {
                return ResourceManager.GetString("ThirdPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of vectors is null..
        /// </summary>
        public static string VectorArrayIsNull {
            get {
                return ResourceManager.GetString("VectorArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of vectors is null..
        /// </summary>
        public static string VectorCollectionIsNull {
            get {
                return ResourceManager.GetString("VectorCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector is null..
        /// </summary>
        public static string VectorIsNull {
            get {
                return ResourceManager.GetString("VectorIsNull", resourceCulture);
            }
        }
    }
}
