//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.AEGIS.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ELTE.AEGIS.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements in the source collection is greater than the available space from the array index to the end of the destination array..
        /// </summary>
        internal static string ArrayIndexIsGreaterThanSpace {
            get {
                return ResourceManager.GetString("ArrayIndexIsGreaterThanSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array is null..
        /// </summary>
        internal static string ArrayIsNull {
            get {
                return ResourceManager.GetString("ArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer is null..
        /// </summary>
        internal static string BufferIsNull {
            get {
                return ResourceManager.GetString("BufferIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capacity is less than 0..
        /// </summary>
        internal static string CapacityLessThan0 {
            get {
                return ResourceManager.GetString("CapacityLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate is null..
        /// </summary>
        internal static string CoordinateIsNull {
            get {
                return ResourceManager.GetString("CoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of coordinates is null..
        /// </summary>
        internal static string CoordinatesArrayIsNull {
            get {
                return ResourceManager.GetString("CoordinatesArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of coordinates is null..
        /// </summary>
        internal static string CoordinatesCollectionIsNull {
            get {
                return ResourceManager.GetString("CoordinatesCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delta is less than or equal to 0..
        /// </summary>
        internal static string DeltaIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("DeltaIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end point is null..
        /// </summary>
        internal static string EndPointIsNull {
            get {
                return ResourceManager.GetString("EndPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The envelope is null..
        /// </summary>
        internal static string EnvelopeIsNull {
            get {
                return ResourceManager.GetString("EnvelopeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge of the event is greater than the number of edges in the source..
        /// </summary>
        internal static string EventEdgeIsGreaterThanNumberOfEdges {
            get {
                return ResourceManager.GetString("EventEdgeIsGreaterThanNumberOfEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge of the event is less than 0..
        /// </summary>
        internal static string EventEdgeIsLessThan0 {
            get {
                return ResourceManager.GetString("EventEdgeIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event is null..
        /// </summary>
        internal static string EventIsNull {
            get {
                return ResourceManager.GetString("EventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory behavior is null..
        /// </summary>
        internal static string FactoryBehaviorIsNull {
            get {
                return ResourceManager.GetString("FactoryBehaviorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory contact is null..
        /// </summary>
        internal static string FactoryContractIsNull {
            get {
                return ResourceManager.GetString("FactoryContractIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory is invalid..
        /// </summary>
        internal static string FactoryIsInvalid {
            get {
                return ResourceManager.GetString("FactoryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory is null..
        /// </summary>
        internal static string FactoryIsNull {
            get {
                return ResourceManager.GetString("FactoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory behavior does not implement the contract..
        /// </summary>
        internal static string FactoryNotImplementingContract {
            get {
                return ResourceManager.GetString("FactoryNotImplementingContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first coordinate is null..
        /// </summary>
        internal static string FirstCoordinateIsNull {
            get {
                return ResourceManager.GetString("FirstCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first point is null..
        /// </summary>
        internal static string FirstPointIsNull {
            get {
                return ResourceManager.GetString("FirstPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first polygon is null..
        /// </summary>
        internal static string FirstPolygonIsNull {
            get {
                return ResourceManager.GetString("FirstPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first vector is null..
        /// </summary>
        internal static string FirstVectorIsNull {
            get {
                return ResourceManager.GetString("FirstVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the geometry is not supported..
        /// </summary>
        internal static string GeometryTypeNotSupported {
            get {
                return ResourceManager.GetString("GeometryTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hole is null..
        /// </summary>
        internal static string HoleIsNull {
            get {
                return ResourceManager.GetString("HoleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holes are not supported in the triangle..
        /// </summary>
        internal static string HolesNotSupportedInTriangle {
            get {
                return ResourceManager.GetString("HolesNotSupportedInTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier is null..
        /// </summary>
        internal static string IdentifierIsNull {
            get {
                return ResourceManager.GetString("IdentifierIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is equal to or greater than the number of holes..
        /// </summary>
        internal static string IndexIsEqualToOrGreaterThanHoleCount {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanHoleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the number of coordinates..
        /// </summary>
        internal static string IndexIsEqualToOrGreaterThanNumberOfCoordinates {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanNumberOfCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is less than 0..
        /// </summary>
        internal static string IndexIsLessThan0 {
            get {
                return ResourceManager.GetString("IndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intersection event is null..
        /// </summary>
        internal static string IntersectionEventIsNull {
            get {
                return ResourceManager.GetString("IntersectionEventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension of lines is not supported..
        /// </summary>
        internal static string LineExtensionNotSupported {
            get {
                return ResourceManager.GetString("LineExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduction of lines is not supported..
        /// </summary>
        internal static string LineReductionNotSupported {
            get {
                return ResourceManager.GetString("LineReductionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of models is null..
        /// </summary>
        internal static string ModelsArrayIsNull {
            get {
                return ResourceManager.GetString("ModelsArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no holes in the polygon..
        /// </summary>
        internal static string NoHolesInPolygon {
            get {
                return ResourceManager.GetString("NoHolesInPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No models are specified..
        /// </summary>
        internal static string NoModelsSpecified {
            get {
                return ResourceManager.GetString("NoModelsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of coordinates is less than 3..
        /// </summary>
        internal static string NumberOfCoordinatesIsLessThan3 {
            get {
                return ResourceManager.GetString("NumberOfCoordinatesIsLessThan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin is null..
        /// </summary>
        internal static string OriginIsNull {
            get {
                return ResourceManager.GetString("OriginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other geometry collection is null..
        /// </summary>
        internal static string OtherGeometryCollectionIsNull {
            get {
                return ResourceManager.GetString("OtherGeometryCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other geometry is null..
        /// </summary>
        internal static string OtherGeometryIsNull {
            get {
                return ResourceManager.GetString("OtherGeometryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other linear ring is null..
        /// </summary>
        internal static string OtherLinearRingIsNull {
            get {
                return ResourceManager.GetString("OtherLinearRingIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other line is null..
        /// </summary>
        internal static string OtherLineIsNull {
            get {
                return ResourceManager.GetString("OtherLineIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other line string is null..
        /// </summary>
        internal static string OtherLineStringIsNull {
            get {
                return ResourceManager.GetString("OtherLineStringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other multi line string is null..
        /// </summary>
        internal static string OtherMultiLineStringIsNull {
            get {
                return ResourceManager.GetString("OtherMultiLineStringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other multi point is null..
        /// </summary>
        internal static string OtherMultiPointIsNull {
            get {
                return ResourceManager.GetString("OtherMultiPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other multi polygon is null..
        /// </summary>
        internal static string OtherMultiPolygonIsNull {
            get {
                return ResourceManager.GetString("OtherMultiPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other point is null..
        /// </summary>
        internal static string OtherPointIsNull {
            get {
                return ResourceManager.GetString("OtherPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other polygon is null..
        /// </summary>
        internal static string OtherPolygonIsNull {
            get {
                return ResourceManager.GetString("OtherPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other triangle is null..
        /// </summary>
        internal static string OtherTriangleIsNull {
            get {
                return ResourceManager.GetString("OtherTriangleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polygon is null..
        /// </summary>
        internal static string PolygonIsNull {
            get {
                return ResourceManager.GetString("PolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is equal to or less than 0..
        /// </summary>
        internal static string ScaleIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("ScaleIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second Coordinate is null..
        /// </summary>
        internal static string SecondCoordinateIsNull {
            get {
                return ResourceManager.GetString("SecondCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second point is null..
        /// </summary>
        internal static string SecondPointIsNull {
            get {
                return ResourceManager.GetString("SecondPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second polygon is null..
        /// </summary>
        internal static string SecondPolygonIsNull {
            get {
                return ResourceManager.GetString("SecondPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second vector is null..
        /// </summary>
        internal static string SecondVectorIsNull {
            get {
                return ResourceManager.GetString("SecondVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segment is null..
        /// </summary>
        internal static string SegmentIsNull {
            get {
                return ResourceManager.GetString("SegmentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segments do not intersect..
        /// </summary>
        internal static string SegmentsDoNotIntersect {
            get {
                return ResourceManager.GetString("SegmentsDoNotIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segments do not overlap..
        /// </summary>
        internal static string SegmentsDoNotOverlap {
            get {
                return ResourceManager.GetString("SegmentsDoNotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shell is null..
        /// </summary>
        internal static string ShellIsNull {
            get {
                return ResourceManager.GetString("ShellIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source is null..
        /// </summary>
        internal static string SourceIsNull {
            get {
                return ResourceManager.GetString("SourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start point is null..
        /// </summary>
        internal static string StartPointIsNull {
            get {
                return ResourceManager.GetString("StartPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The third point is null..
        /// </summary>
        internal static string ThirdPointIsNull {
            get {
                return ResourceManager.GetString("ThirdPointIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of vectors is null..
        /// </summary>
        internal static string VectorArrayIsNull {
            get {
                return ResourceManager.GetString("VectorArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of vectors is null..
        /// </summary>
        internal static string VectorCollectionIsNull {
            get {
                return ResourceManager.GetString("VectorCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector is null..
        /// </summary>
        internal static string VectorIsNull {
            get {
                return ResourceManager.GetString("VectorIsNull", resourceCulture);
            }
        }
    }
}
