//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.AEGIS.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ELTE.AEGIS.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate is null..
        /// </summary>
        internal static string CoordinateIsNull {
            get {
                return ResourceManager.GetString("CoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of coordinates is null..
        /// </summary>
        internal static string CoordinatesArrayIsNull {
            get {
                return ResourceManager.GetString("CoordinatesArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of coordinates is null..
        /// </summary>
        internal static string CoordinatesCollectionIsNull {
            get {
                return ResourceManager.GetString("CoordinatesCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The envelope is null..
        /// </summary>
        internal static string EnvelopeIsNull {
            get {
                return ResourceManager.GetString("EnvelopeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first coordinate is null..
        /// </summary>
        internal static string FirstCoordinateIsNull {
            get {
                return ResourceManager.GetString("FirstCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first vector is null..
        /// </summary>
        internal static string FirstVectorIsNull {
            get {
                return ResourceManager.GetString("FirstVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of models is null..
        /// </summary>
        internal static string ModelsArrayIsNull {
            get {
                return ResourceManager.GetString("ModelsArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No models are specified..
        /// </summary>
        internal static string NoModelsSpecified {
            get {
                return ResourceManager.GetString("NoModelsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin is null..
        /// </summary>
        internal static string OriginIsNull {
            get {
                return ResourceManager.GetString("OriginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is equal to or less than 0..
        /// </summary>
        internal static string ScaleIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("ScaleIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second Coordinate is null..
        /// </summary>
        internal static string SecondCoordinateIsNull {
            get {
                return ResourceManager.GetString("SecondCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second vector is null..
        /// </summary>
        internal static string SecondVectorIsNull {
            get {
                return ResourceManager.GetString("SecondVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of vectors is null..
        /// </summary>
        internal static string VectorArrayIsNull {
            get {
                return ResourceManager.GetString("VectorArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of vectors is null..
        /// </summary>
        internal static string VectorCollectionIsNull {
            get {
                return ResourceManager.GetString("VectorCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector is null..
        /// </summary>
        internal static string VectorIsNull {
            get {
                return ResourceManager.GetString("VectorIsNull", resourceCulture);
            }
        }
    }
}
