//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.AEGIS.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ELTE.AEGIS.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate is null..
        /// </summary>
        internal static string CoordinateIsNull {
            get {
                return ResourceManager.GetString("CoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of coordinates is null..
        /// </summary>
        internal static string CoordinatesArrayIsNull {
            get {
                return ResourceManager.GetString("CoordinatesArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of coordinates is null..
        /// </summary>
        internal static string CoordinatesCollectionIsNull {
            get {
                return ResourceManager.GetString("CoordinatesCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delta is less than or equal to 0..
        /// </summary>
        internal static string DeltaIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("DeltaIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The envelope is null..
        /// </summary>
        internal static string EnvelopeIsNull {
            get {
                return ResourceManager.GetString("EnvelopeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge of the event is greater than the number of edges in the source..
        /// </summary>
        internal static string EventEdgeIsGreaterThanNumberOfEdges {
            get {
                return ResourceManager.GetString("EventEdgeIsGreaterThanNumberOfEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge of the event is less than 0..
        /// </summary>
        internal static string EventEdgeIsLessThan0 {
            get {
                return ResourceManager.GetString("EventEdgeIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event is null..
        /// </summary>
        internal static string EventIsNull {
            get {
                return ResourceManager.GetString("EventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first coordinate is null..
        /// </summary>
        internal static string FirstCoordinateIsNull {
            get {
                return ResourceManager.GetString("FirstCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first polygon is null..
        /// </summary>
        internal static string FirstPolygonIsNull {
            get {
                return ResourceManager.GetString("FirstPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first vector is null..
        /// </summary>
        internal static string FirstVectorIsNull {
            get {
                return ResourceManager.GetString("FirstVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier is null..
        /// </summary>
        internal static string IdentifierIsNull {
            get {
                return ResourceManager.GetString("IdentifierIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is equal to or greater than the number of holes..
        /// </summary>
        internal static string IndexIsEqualToOrGreaterThanHoleCount {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanHoleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the number of coordinates..
        /// </summary>
        internal static string IndexIsEqualToOrGreaterThanNumberOfCoordinates {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanNumberOfCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is less than 0..
        /// </summary>
        internal static string IndexIsLessThan0 {
            get {
                return ResourceManager.GetString("IndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intersection event is null..
        /// </summary>
        internal static string IntersectionEventIsNull {
            get {
                return ResourceManager.GetString("IntersectionEventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of models is null..
        /// </summary>
        internal static string ModelsArrayIsNull {
            get {
                return ResourceManager.GetString("ModelsArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no holes in the polygon..
        /// </summary>
        internal static string NoHolesInPolygon {
            get {
                return ResourceManager.GetString("NoHolesInPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No models are specified..
        /// </summary>
        internal static string NoModelsSpecified {
            get {
                return ResourceManager.GetString("NoModelsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin is null..
        /// </summary>
        internal static string OriginIsNull {
            get {
                return ResourceManager.GetString("OriginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polygon is null..
        /// </summary>
        internal static string PolygonIsNull {
            get {
                return ResourceManager.GetString("PolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is equal to or less than 0..
        /// </summary>
        internal static string ScaleIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("ScaleIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second Coordinate is null..
        /// </summary>
        internal static string SecondCoordinateIsNull {
            get {
                return ResourceManager.GetString("SecondCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second polygon is null..
        /// </summary>
        internal static string SecondPolygonIsNull {
            get {
                return ResourceManager.GetString("SecondPolygonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second vector is null..
        /// </summary>
        internal static string SecondVectorIsNull {
            get {
                return ResourceManager.GetString("SecondVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segment is null..
        /// </summary>
        internal static string SegmentIsNull {
            get {
                return ResourceManager.GetString("SegmentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segments do not intersect..
        /// </summary>
        internal static string SegmentsDoNotIntersect {
            get {
                return ResourceManager.GetString("SegmentsDoNotIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segments do not overlap..
        /// </summary>
        internal static string SegmentsDoNotOverlap {
            get {
                return ResourceManager.GetString("SegmentsDoNotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shell is null..
        /// </summary>
        internal static string ShellIsNull {
            get {
                return ResourceManager.GetString("ShellIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source is null..
        /// </summary>
        internal static string SourceIsNull {
            get {
                return ResourceManager.GetString("SourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of vectors is null..
        /// </summary>
        internal static string VectorArrayIsNull {
            get {
                return ResourceManager.GetString("VectorArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of vectors is null..
        /// </summary>
        internal static string VectorCollectionIsNull {
            get {
                return ResourceManager.GetString("VectorCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector is null..
        /// </summary>
        internal static string VectorIsNull {
            get {
                return ResourceManager.GetString("VectorIsNull", resourceCulture);
            }
        }
    }
}
