//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.AEGIS.Collections.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ELTE.AEGIS.Collections.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements in the source collection is greater than the available space from the array index to the end of the destination array..
        /// </summary>
        internal static string ArrayIndexIsGreaterThanSpace {
            get {
                return ResourceManager.GetString("ArrayIndexIsGreaterThanSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array index is less than 0..
        /// </summary>
        internal static string ArrayIndexIsLessThan0 {
            get {
                return ResourceManager.GetString("ArrayIndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array is null..
        /// </summary>
        internal static string ArrayIsNull {
            get {
                return ResourceManager.GetString("ArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capacity is less than 0..
        /// </summary>
        internal static string CapacityLessThan0 {
            get {
                return ResourceManager.GetString("CapacityLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity is set to a value that is less than Count..
        /// </summary>
        internal static string CapacityLessThanCount {
            get {
                return ResourceManager.GetString("CapacityLessThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is empty..
        /// </summary>
        internal static string CollectionIsEmpty {
            get {
                return ResourceManager.GetString("CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is null..
        /// </summary>
        internal static string CollectionIsNull {
            get {
                return ResourceManager.GetString("CollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection was modified after the enumerator was created..
        /// </summary>
        internal static string CollectionWasModifiedAfterEnumerator {
            get {
                return ResourceManager.GetString("CollectionWasModifiedAfterEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count is less than 1..
        /// </summary>
        internal static string CountIsLessThan1 {
            get {
                return ResourceManager.GetString("CountIsLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary is null..
        /// </summary>
        internal static string DictionaryIsNull {
            get {
                return ResourceManager.GetString("DictionaryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first item is not present in any set..
        /// </summary>
        internal static string FirstItemIsNotPresentInAnySet {
            get {
                return ResourceManager.GetString("FirstItemIsNotPresentInAnySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first item is null..
        /// </summary>
        internal static string FirstItemIsNull {
            get {
                return ResourceManager.GetString("FirstItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heap is empty..
        /// </summary>
        internal static string HeapIsEmpty {
            get {
                return ResourceManager.GetString("HeapIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heap is null..
        /// </summary>
        internal static string HeapIsNull {
            get {
                return ResourceManager.GetString("HeapIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the number of items in the array..
        /// </summary>
        internal static string IndexIsEqualToOrGreaterThanArraySize {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the count..
        /// </summary>
        internal static string IndexIsEqualToOrGreaterThanCount {
            get {
                return ResourceManager.GetString("IndexIsEqualToOrGreaterThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is less than 0..
        /// </summary>
        internal static string IndexIsLessThan0 {
            get {
                return ResourceManager.GetString("IndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not present in any set..
        /// </summary>
        internal static string ItemIsNotPresentInAnySet {
            get {
                return ResourceManager.GetString("ItemIsNotPresentInAnySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is null..
        /// </summary>
        internal static string ItemIsNull {
            get {
                return ResourceManager.GetString("ItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element with the same key already exists in the tree..
        /// </summary>
        internal static string KeyExists {
            get {
                return ResourceManager.GetString("KeyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is null..
        /// </summary>
        internal static string KeyIsNull {
            get {
                return ResourceManager.GetString("KeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tree does not contain the specified key..
        /// </summary>
        internal static string KeyNotExists {
            get {
                return ResourceManager.GetString("KeyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length is less than 0..
        /// </summary>
        internal static string LengthIsLessThan0 {
            get {
                return ResourceManager.GetString("LengthIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predicate is null..
        /// </summary>
        internal static string PredicateIsNull {
            get {
                return ResourceManager.GetString("PredicateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second item is not present in any set..
        /// </summary>
        internal static string SecondItemIsNotPresentInAnySet {
            get {
                return ResourceManager.GetString("SecondItemIsNotPresentInAnySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second item is null..
        /// </summary>
        internal static string SecondItemIsNull {
            get {
                return ResourceManager.GetString("SecondItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector is null..
        /// </summary>
        internal static string SelectorIsNull {
            get {
                return ResourceManager.GetString("SelectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set is null..
        /// </summary>
        internal static string SetIsNull {
            get {
                return ResourceManager.GetString("SetIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set is read-only..
        /// </summary>
        internal static string SetIsReadOnly {
            get {
                return ResourceManager.GetString("SetIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source is null..
        /// </summary>
        internal static string SourceIsNull {
            get {
                return ResourceManager.GetString("SourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array contains more elements than the maximum value..
        /// </summary>
        internal static string TooManyElementsInArray {
            get {
                return ResourceManager.GetString("TooManyElementsInArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tree is null..
        /// </summary>
        internal static string TreeIsNull {
            get {
                return ResourceManager.GetString("TreeIsNull", resourceCulture);
            }
        }
    }
}
