//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.AEGIS.Reference.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ELTE.AEGIS.Reference.Resources.ReferenceMessages", typeof(ReferenceMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of angles is null..
        /// </summary>
        internal static string AngleArrayIsNull {
            get {
                return ResourceManager.GetString("AngleArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of angles is null..
        /// </summary>
        internal static string AngleCollectionIsNull {
            get {
                return ResourceManager.GetString("AngleCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The angular unit of measurement is invalid..
        /// </summary>
        internal static string AngularUnitOfMeasurementIsInvalid {
            get {
                return ResourceManager.GetString("AngularUnitOfMeasurementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The angular unit of measurement is null..
        /// </summary>
        internal static string AngularUnitOfMeasurementIsNull {
            get {
                return ResourceManager.GetString("AngularUnitOfMeasurementIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area of use source is null..
        /// </summary>
        internal static string AreaOfUseCollectionIsNull {
            get {
                return ResourceManager.GetString("AreaOfUseCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area of use is null..
        /// </summary>
        internal static string AreaOfUseIsNull {
            get {
                return ResourceManager.GetString("AreaOfUseIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate system axis collection is null..
        /// </summary>
        internal static string AxisCollectionIsNull {
            get {
                return ResourceManager.GetString("AxisCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate system does not contain an axis with the specified name..
        /// </summary>
        internal static string AxisNameIsInvalid {
            get {
                return ResourceManager.GetString("AxisNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The axis name is null..
        /// </summary>
        internal static string AxisNameIsNull {
            get {
                return ResourceManager.GetString("AxisNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base multiple is 0..
        /// </summary>
        internal static string BaseMultipleIs0 {
            get {
                return ResourceManager.GetString("BaseMultipleIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base reference system collection is null..
        /// </summary>
        internal static string BaseReferenceSystemCollectionsIsNull {
            get {
                return ResourceManager.GetString("BaseReferenceSystemCollectionsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base reference system is null..
        /// </summary>
        internal static string BaseReferenceSystemIsNull {
            get {
                return ResourceManager.GetString("BaseReferenceSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection container is null..
        /// </summary>
        internal static string CollectionContainerIsNull {
            get {
                return ResourceManager.GetString("CollectionContainerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is null..
        /// </summary>
        internal static string CollectionIsNull {
            get {
                return ResourceManager.GetString("CollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion does not exist between the specified reference systems..
        /// </summary>
        internal static string ConversionDoesNotExistBetweenReferenceSystems {
            get {
                return ResourceManager.GetString("ConversionDoesNotExistBetweenReferenceSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion is null..
        /// </summary>
        internal static string ConversionIsNull {
            get {
                return ResourceManager.GetString("ConversionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate is null..
        /// </summary>
        internal static string CoordinateIsNull {
            get {
                return ResourceManager.GetString("CoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate projection collection is null..
        /// </summary>
        internal static string CoordinateProjectionCollectionIsNull {
            get {
                return ResourceManager.GetString("CoordinateProjectionCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coordinates are specified..
        /// </summary>
        internal static string CoordinatesAreNull {
            get {
                return ResourceManager.GetString("CoordinatesAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate system collection is null..
        /// </summary>
        internal static string CoordinateSystemCollectionIsNull {
            get {
                return ResourceManager.GetString("CoordinateSystemCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension of the coordinate system is less than expected..
        /// </summary>
        internal static string CoordinateSystemDimensionLessThanExpected {
            get {
                return ResourceManager.GetString("CoordinateSystemDimensionLessThanExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate system is null..
        /// </summary>
        internal static string CoordinateSystemIsNull {
            get {
                return ResourceManager.GetString("CoordinateSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The datum collection is null..
        /// </summary>
        internal static string DatumCollectionIsNull {
            get {
                return ResourceManager.GetString("DatumCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The datum is null..
        /// </summary>
        internal static string DatumIsNull {
            get {
                return ResourceManager.GetString("DatumIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination coordinate is null..
        /// </summary>
        internal static string DestinationCoordinateIsNull {
            get {
                return ResourceManager.GetString("DestinationCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eccentricity is equal to or less than 0..
        /// </summary>
        internal static string EccentricityIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("EccentricityIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eccentricity greater than 1..
        /// </summary>
        internal static string EccentricityIsGreaterThan1 {
            get {
                return ResourceManager.GetString("EccentricityIsGreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ellipsoid collection is null..
        /// </summary>
        internal static string EllipsoidCollectionIsNull {
            get {
                return ResourceManager.GetString("EllipsoidCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ellipsoid is null..
        /// </summary>
        internal static string EllipsoidIsNull {
            get {
                return ResourceManager.GetString("EllipsoidIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flattening is equal to or less than 0..
        /// </summary>
        internal static string FlatteningIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("FlatteningIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flattening greater than 1..
        /// </summary>
        internal static string FlatteningIsGreaterThan1 {
            get {
                return ResourceManager.GetString("FlatteningIsGreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier is null..
        /// </summary>
        internal static string IdentifierIsNull {
            get {
                return ResourceManager.GetString("IdentifierIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the number of axis..
        /// </summary>
        internal static string IndexEqualToOrGreaterThanAxisCount {
            get {
                return ResourceManager.GetString("IndexEqualToOrGreaterThanAxisCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is less than 0..
        /// </summary>
        internal static string IndexIsLessThan0 {
            get {
                return ResourceManager.GetString("IndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inverse flattening is less than 1..
        /// </summary>
        internal static string InverseFlatteningLessThan1 {
            get {
                return ResourceManager.GetString("InverseFlatteningLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude is invalid..
        /// </summary>
        internal static string LatitudeInvalid {
            get {
                return ResourceManager.GetString("LatitudeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of length values is null..
        /// </summary>
        internal static string LengthArrayIsNull {
            get {
                return ResourceManager.GetString("LengthArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of length values is null..
        /// </summary>
        internal static string LengthCollectionIsNull {
            get {
                return ResourceManager.GetString("LengthCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length unit of measurement is invalid..
        /// </summary>
        internal static string LengthUnitOfMeasurementIsInvalid {
            get {
                return ResourceManager.GetString("LengthUnitOfMeasurementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length unit of measurement is null..
        /// </summary>
        internal static string LengthUnitOfMeasurementIsNull {
            get {
                return ResourceManager.GetString("LengthUnitOfMeasurementIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude value is not between -180 and 180 degrees..
        /// </summary>
        internal static string LongitudeOutOfRangeDegrees {
            get {
                return ResourceManager.GetString("LongitudeOutOfRangeDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude value is not between -PI and +PI radians..
        /// </summary>
        internal static string LongitudeOutOfRangeRadians {
            get {
                return ResourceManager.GetString("LongitudeOutOfRangeRadians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value is equal to or less than the minimum value..
        /// </summary>
        internal static string MaximumIsEqualToOrLessThanMinimum {
            get {
                return ResourceManager.GetString("MaximumIsEqualToOrLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meridian collection is null..
        /// </summary>
        internal static string MeridianCollectionIsNull {
            get {
                return ResourceManager.GetString("MeridianCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate operation method collection is null..
        /// </summary>
        internal static string MethodCollectionIsNull {
            get {
                return ResourceManager.GetString("MethodCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified method does not contain 3 internal methods..
        /// </summary>
        internal static string MethodInternalsNot3 {
            get {
                return ResourceManager.GetString("MethodInternalsNot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified method does not contain 5 internal methods..
        /// </summary>
        internal static string MethodInternalsNot5 {
            get {
                return ResourceManager.GetString("MethodInternalsNot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method is null..
        /// </summary>
        internal static string MethodIsNull {
            get {
                return ResourceManager.GetString("MethodIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is null..
        /// </summary>
        internal static string NameIsNull {
            get {
                return ResourceManager.GetString("NameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No axis is specified for the coordinate system..
        /// </summary>
        internal static string NoAxisSpecified {
            get {
                return ResourceManager.GetString("NoAxisSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No components are specified..
        /// </summary>
        internal static string NoComponentsAreSpecified {
            get {
                return ResourceManager.GetString("NoComponentsAreSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No methods are specified..
        /// </summary>
        internal static string NoMethodsSpecified {
            get {
                return ResourceManager.GetString("NoMethodsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate operation is not reversible..
        /// </summary>
        internal static string OperationNotReversible {
            get {
                return ResourceManager.GetString("OperationNotReversible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other envelope is null..
        /// </summary>
        internal static string OtherEnvelopeIsNull {
            get {
                return ResourceManager.GetString("OtherEnvelopeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate operation parameter collection is null..
        /// </summary>
        internal static string ParameterCollectionIsNull {
            get {
                return ResourceManager.GetString("ParameterCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No general polynomial transformation is available for the given degree..
        /// </summary>
        internal static string PolynomialTransformationDegreeIsInvalid {
            get {
                return ResourceManager.GetString("PolynomialTransformationDegreeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prime meridian is null..
        /// </summary>
        internal static string PrimeMeridianIsNull {
            get {
                return ResourceManager.GetString("PrimeMeridianIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The projection is null..
        /// </summary>
        internal static string ProjectionIsNull {
            get {
                return ResourceManager.GetString("ProjectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference system collection is null..
        /// </summary>
        internal static string ReferenceSystemCollectionIsNull {
            get {
                return ResourceManager.GetString("ReferenceSystemCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference system is null..
        /// </summary>
        internal static string ReferenceSystemIsNull {
            get {
                return ResourceManager.GetString("ReferenceSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi axis is equal to or less than 0..
        /// </summary>
        internal static string SemiAxisIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("SemiAxisIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-major axis is equal to or less than 0..
        /// </summary>
        internal static string SemiMajorAxisIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("SemiMajorAxisIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-minor axis is not measured in the same measurement unit as the semi-major axis..
        /// </summary>
        internal static string SemiMajorAxisUnitNotEqualToSemiMinorAxisUnit {
            get {
                return ResourceManager.GetString("SemiMajorAxisUnitNotEqualToSemiMinorAxisUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-minor axis is grater than the semi-major axis..
        /// </summary>
        internal static string SemiMinorAxisGreaterThaneSemiMajorAxis {
            get {
                return ResourceManager.GetString("SemiMinorAxisGreaterThaneSemiMajorAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-minor axis is equal to or less than 0..
        /// </summary>
        internal static string SemiMinorAxisIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("SemiMinorAxisIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source coordinate is null..
        /// </summary>
        internal static string SourceCoordinateIsNull {
            get {
                return ResourceManager.GetString("SourceCoordinateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source coordinate reference system is null..
        /// </summary>
        internal static string SourceCoordinateReferenceSystemIsNull {
            get {
                return ResourceManager.GetString("SourceCoordinateReferenceSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source reference system is null..
        /// </summary>
        internal static string SourceReferenceSystemIsNull {
            get {
                return ResourceManager.GetString("SourceReferenceSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target coordinate reference system is null..
        /// </summary>
        internal static string TargetCoordinateReferenceSystemIsNull {
            get {
                return ResourceManager.GetString("TargetCoordinateReferenceSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target reference system is null..
        /// </summary>
        internal static string TargetReferenceSystemIsNull {
            get {
                return ResourceManager.GetString("TargetReferenceSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transformation is null..
        /// </summary>
        internal static string TransformationIsNull {
            get {
                return ResourceManager.GetString("TransformationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measurement is not a length measure..
        /// </summary>
        internal static string UnitIsNotLength {
            get {
                return ResourceManager.GetString("UnitIsNotLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measurement is null..
        /// </summary>
        internal static string UnitIsNull {
            get {
                return ResourceManager.GetString("UnitIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measurement collection is null..
        /// </summary>
        internal static string UnitOfMeasurementCollectionIsNull {
            get {
                return ResourceManager.GetString("UnitOfMeasurementCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measurement is invalid..
        /// </summary>
        internal static string UnitOfMeasurementIsInvalid {
            get {
                return ResourceManager.GetString("UnitOfMeasurementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measurement is null..
        /// </summary>
        internal static string UnitOfMeasurementIsNull {
            get {
                return ResourceManager.GetString("UnitOfMeasurementIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector computation is only supported on sphere..
        /// </summary>
        internal static string VectorComputationOnlySupportedOnSphere {
            get {
                return ResourceManager.GetString("VectorComputationOnlySupportedOnSphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector is null..
        /// </summary>
        internal static string VectorIsNull {
            get {
                return ResourceManager.GetString("VectorIsNull", resourceCulture);
            }
        }
    }
}
