//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEGIS.Reference.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AEGIS.Reference.Resources.ReferenceMessages", typeof(ReferenceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The angular unit of measurement is invalid..
        /// </summary>
        internal static string AngularUnitOfMeasurementIsInvalid {
            get {
                return ResourceManager.GetString("AngularUnitOfMeasurementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate system does not contain an axis with the specified name..
        /// </summary>
        internal static string AxisNameIsInvalid {
            get {
                return ResourceManager.GetString("AxisNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base multiple is 0..
        /// </summary>
        internal static string BaseMultipleIs0 {
            get {
                return ResourceManager.GetString("BaseMultipleIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion does not exist between the specified reference systems..
        /// </summary>
        internal static string ConversionDoesNotExistBetweenReferenceSystems {
            get {
                return ResourceManager.GetString("ConversionDoesNotExistBetweenReferenceSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coordinates are specified..
        /// </summary>
        internal static string CoordinatesAreNull {
            get {
                return ResourceManager.GetString("CoordinatesAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension of the coordinate system is less than expected..
        /// </summary>
        internal static string CoordinateSystemDimensionLessThanExpected {
            get {
                return ResourceManager.GetString("CoordinateSystemDimensionLessThanExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eccentricity is equal to or less than 0..
        /// </summary>
        internal static string EccentricityIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("EccentricityIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eccentricity greater than 1..
        /// </summary>
        internal static string EccentricityIsGreaterThan1 {
            get {
                return ResourceManager.GetString("EccentricityIsGreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flattening is equal to or less than 0..
        /// </summary>
        internal static string FlatteningIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("FlatteningIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flattening greater than 1..
        /// </summary>
        internal static string FlatteningIsGreaterThan1 {
            get {
                return ResourceManager.GetString("FlatteningIsGreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the number of axis..
        /// </summary>
        internal static string IndexEqualToOrGreaterThanAxisCount {
            get {
                return ResourceManager.GetString("IndexEqualToOrGreaterThanAxisCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is less than 0..
        /// </summary>
        internal static string IndexIsLessThan0 {
            get {
                return ResourceManager.GetString("IndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inverse flattening is less than 1..
        /// </summary>
        internal static string InverseFlatteningLessThan1 {
            get {
                return ResourceManager.GetString("InverseFlatteningLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude is invalid..
        /// </summary>
        internal static string LatitudeInvalid {
            get {
                return ResourceManager.GetString("LatitudeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length unit of measurement is invalid..
        /// </summary>
        internal static string LengthUnitOfMeasurementIsInvalid {
            get {
                return ResourceManager.GetString("LengthUnitOfMeasurementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude value is not between -180 and 180 degrees..
        /// </summary>
        internal static string LongitudeOutOfRangeDegrees {
            get {
                return ResourceManager.GetString("LongitudeOutOfRangeDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude value is not between -PI and +PI radians..
        /// </summary>
        internal static string LongitudeOutOfRangeRadians {
            get {
                return ResourceManager.GetString("LongitudeOutOfRangeRadians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value is equal to or less than the minimum value..
        /// </summary>
        internal static string MaximumIsEqualToOrLessThanMinimum {
            get {
                return ResourceManager.GetString("MaximumIsEqualToOrLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified method does not contain 3 internal methods..
        /// </summary>
        internal static string MethodInternalsNot3 {
            get {
                return ResourceManager.GetString("MethodInternalsNot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified method does not contain 5 internal methods..
        /// </summary>
        internal static string MethodInternalsNot5 {
            get {
                return ResourceManager.GetString("MethodInternalsNot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No axis is specified for the coordinate system..
        /// </summary>
        internal static string NoAxisSpecified {
            get {
                return ResourceManager.GetString("NoAxisSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No components are specified..
        /// </summary>
        internal static string NoComponentsAreSpecified {
            get {
                return ResourceManager.GetString("NoComponentsAreSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No methods are specified..
        /// </summary>
        internal static string NoMethodsSpecified {
            get {
                return ResourceManager.GetString("NoMethodsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate operation is not reversible..
        /// </summary>
        internal static string OperationNotReversible {
            get {
                return ResourceManager.GetString("OperationNotReversible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No general polynomial transformation is available for the given degree..
        /// </summary>
        internal static string PolynomialTransformationDegreeIsInvalid {
            get {
                return ResourceManager.GetString("PolynomialTransformationDegreeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi axis is equal to or less than 0..
        /// </summary>
        internal static string SemiAxisIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("SemiAxisIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-major axis is equal to or less than 0..
        /// </summary>
        internal static string SemiMajorAxisIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("SemiMajorAxisIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-minor axis is not measured in the same measurement unit as the semi-major axis..
        /// </summary>
        internal static string SemiMajorAxisUnitNotEqualToSemiMinorAxisUnit {
            get {
                return ResourceManager.GetString("SemiMajorAxisUnitNotEqualToSemiMinorAxisUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-minor axis is grater than the semi-major axis..
        /// </summary>
        internal static string SemiMinorAxisGreaterThaneSemiMajorAxis {
            get {
                return ResourceManager.GetString("SemiMinorAxisGreaterThaneSemiMajorAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-minor axis is equal to or less than 0..
        /// </summary>
        internal static string SemiMinorAxisIsEqualToOrLessThan0 {
            get {
                return ResourceManager.GetString("SemiMinorAxisIsEqualToOrLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measurement is not a length measure..
        /// </summary>
        internal static string UnitIsNotLength {
            get {
                return ResourceManager.GetString("UnitIsNotLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measurement is invalid..
        /// </summary>
        internal static string UnitOfMeasurementIsInvalid {
            get {
                return ResourceManager.GetString("UnitOfMeasurementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector computation is only supported on sphere..
        /// </summary>
        internal static string VectorComputationOnlySupportedOnSphere {
            get {
                return ResourceManager.GetString("VectorComputationOnlySupportedOnSphere", resourceCulture);
            }
        }
    }
}
