//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEGIS.Numerics.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NumericsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumericsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AEGIS.Numerics.Resources.NumericsMessages", typeof(NumericsMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer is null..
        /// </summary>
        public static string BufferIsNull {
            get {
                return ResourceManager.GetString("BufferIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column index is outside the bounds of the matrix..
        /// </summary>
        public static string ColumnIndexOutsideMatrixBounds {
            get {
                return ResourceManager.GetString("ColumnIndexOutsideMatrixBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The denominator is 0..
        /// </summary>
        public static string DenomatorIs0 {
            get {
                return ResourceManager.GetString("DenomatorIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first coefficient is less than 0..
        /// </summary>
        public static string FirstCoefficientIsLessThan0 {
            get {
                return ResourceManager.GetString("FirstCoefficientIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first collection is null..
        /// </summary>
        public static string FirstCollectionIsNull {
            get {
                return ResourceManager.GetString("FirstCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first matrix is null..
        /// </summary>
        public static string FirstMatrixIsNull {
            get {
                return ResourceManager.GetString("FirstMatrixIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first vector is null..
        /// </summary>
        public static string FirstVectorIsNull {
            get {
                return ResourceManager.GetString("FirstVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function is null..
        /// </summary>
        public static string FunctionIsNull {
            get {
                return ResourceManager.GetString("FunctionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is outside the bounds of the vector..
        /// </summary>
        public static string IndexIsOutsideVectorBounds {
            get {
                return ResourceManager.GetString("IndexIsOutsideVectorBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of intervals is not positive even..
        /// </summary>
        public static string IntervalsNotPositiveEven {
            get {
                return ResourceManager.GetString("IntervalsNotPositiveEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is empty..
        /// </summary>
        public static string MatrixIsEmpty {
            get {
                return ResourceManager.GetString("MatrixIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is not invertible..
        /// </summary>
        public static string MatrixIsNotInvertible {
            get {
                return ResourceManager.GetString("MatrixIsNotInvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is not square..
        /// </summary>
        public static string MatrixIsNotSquare {
            get {
                return ResourceManager.GetString("MatrixIsNotSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is not symmetric..
        /// </summary>
        public static string MatrixIsNotSymmetric {
            get {
                return ResourceManager.GetString("MatrixIsNotSymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is null..
        /// </summary>
        public static string MatrixIsNull {
            get {
                return ResourceManager.GetString("MatrixIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is neither single column, nor single row..
        /// </summary>
        public static string MatrixNotSingleColumnOrRow {
            get {
                return ResourceManager.GetString("MatrixNotSingleColumnOrRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows in the matrix is not 1..
        /// </summary>
        public static string MatrixRowsMoreThan1 {
            get {
                return ResourceManager.GetString("MatrixRowsMoreThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the matrix does not match the size of the vector..
        /// </summary>
        public static string MatrixSizeDoesNotMatchVector {
            get {
                return ResourceManager.GetString("MatrixSizeDoesNotMatchVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value is less than 0..
        /// </summary>
        public static string MaxValueLessThan0 {
            get {
                return ResourceManager.GetString("MaxValueLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value is greater than the maximum value..
        /// </summary>
        public static string MinValueGreaterThanMaxValue {
            get {
                return ResourceManager.GetString("MinValueGreaterThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns does not match..
        /// </summary>
        public static string NumberOfColumnsDoesNotMatch {
            get {
                return ResourceManager.GetString("NumberOfColumnsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns is less than 0..
        /// </summary>
        public static string NumberOfColumnsIsLessThan0 {
            get {
                return ResourceManager.GetString("NumberOfColumnsIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of iterations is less than 1..
        /// </summary>
        public static string NumberOfIterationsIsLessThan1 {
            get {
                return ResourceManager.GetString("NumberOfIterationsIsLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows does not match..
        /// </summary>
        public static string NumberOfRowsDoesNotMatch {
            get {
                return ResourceManager.GetString("NumberOfRowsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns in the first matrix does not match the number of rows in the second matrix..
        /// </summary>
        public static string NumberOfRowsDoesNotMatchColumnsMatrix {
            get {
                return ResourceManager.GetString("NumberOfRowsDoesNotMatchColumnsMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows is less than 0..
        /// </summary>
        public static string NumberOfRowsIsLessThan0 {
            get {
                return ResourceManager.GetString("NumberOfRowsIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of values is not a square number..
        /// </summary>
        public static string NumberOfValuesIsNotSquare {
            get {
                return ResourceManager.GetString("NumberOfValuesIsNotSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is not comparable with a rational number..
        /// </summary>
        public static string ObjectIsNotComparableWithRational {
            get {
                return ResourceManager.GetString("ObjectIsNotComparableWithRational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is null..
        /// </summary>
        public static string ObjectIsNull {
            get {
                return ResourceManager.GetString("ObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other matrix is null..
        /// </summary>
        public static string OtherMatrixIsNull {
            get {
                return ResourceManager.GetString("OtherMatrixIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other vector is null..
        /// </summary>
        public static string OtherVectorIsNull {
            get {
                return ResourceManager.GetString("OtherVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of p is less than 1..
        /// </summary>
        public static string PIsLessThan1 {
            get {
                return ResourceManager.GetString("PIsLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The random generator is null..
        /// </summary>
        public static string RandomIsNull {
            get {
                return ResourceManager.GetString("RandomIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is too large or too small to be converted to rational..
        /// </summary>
        public static string RationalConversionOutOfRange {
            get {
                return ResourceManager.GetString("RationalConversionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row index is outside the bounds of the matrix..
        /// </summary>
        public static string RowIndexOutsideMatrixBounds {
            get {
                return ResourceManager.GetString("RowIndexOutsideMatrixBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second coefficient is less than 0..
        /// </summary>
        public static string SecondCoefficientIsLessThan0 {
            get {
                return ResourceManager.GetString("SecondCoefficientIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second collection is null..
        /// </summary>
        public static string SecondCollectionIsNull {
            get {
                return ResourceManager.GetString("SecondCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second matrix is null..
        /// </summary>
        public static string SecondMatrixIsNull {
            get {
                return ResourceManager.GetString("SecondMatrixIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second vector is null..
        /// </summary>
        public static string SecondVectorIsNull {
            get {
                return ResourceManager.GetString("SecondVectorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size is less than 0..
        /// </summary>
        public static string SizeIsLessThan0 {
            get {
                return ResourceManager.GetString("SizeIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source is null..
        /// </summary>
        public static string SourceIsNull {
            get {
                return ResourceManager.GetString("SourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit index is greater than or equal to the size..
        /// </summary>
        public static string UnitIndexIsGeaterThanSize {
            get {
                return ResourceManager.GetString("UnitIndexIsGeaterThanSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit index is less than 0..
        /// </summary>
        public static string UnitIndexIsLessThan0 {
            get {
                return ResourceManager.GetString("UnitIndexIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of values is empty..
        /// </summary>
        public static string ValueCollectionIsEmpty {
            get {
                return ResourceManager.GetString("ValueCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of values is null..
        /// </summary>
        public static string ValueCollectionIsNull {
            get {
                return ResourceManager.GetString("ValueCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is less than 0..
        /// </summary>
        public static string ValueIsLessThan0 {
            get {
                return ResourceManager.GetString("ValueIsLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is less than or equal to 0..
        /// </summary>
        public static string ValueIsLessThanOrEqualTo0 {
            get {
                return ResourceManager.GetString("ValueIsLessThanOrEqualTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of value pairs is null..
        /// </summary>
        public static string ValuePairCollectionIsNull {
            get {
                return ResourceManager.GetString("ValuePairCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values are not specified..
        /// </summary>
        public static string ValuesIsNull {
            get {
                return ResourceManager.GetString("ValuesIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimensions of the two vectors are different..
        /// </summary>
        public static string VectorDimensionsAreDifferent {
            get {
                return ResourceManager.GetString("VectorDimensionsAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector is null..
        /// </summary>
        public static string VectorIsNull {
            get {
                return ResourceManager.GetString("VectorIsNull", resourceCulture);
            }
        }
    }
}
