//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.AEGIS.Storage.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ELTE.AEGIS.Storage.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication is not supported..
        /// </summary>
        internal static string AuthenticationIsNotSupported {
            get {
                return ResourceManager.GetString("AuthenticationIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication is null..
        /// </summary>
        internal static string AuthenticationIsNull {
            get {
                return ResourceManager.GetString("AuthenticationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path already exists..
        /// </summary>
        internal static string DestinationPathExists {
            get {
                return ResourceManager.GetString("DestinationPathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path is in an invalid format..
        /// </summary>
        internal static string DestinationPathInvalidFormat {
            get {
                return ResourceManager.GetString("DestinationPathInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path is empty, or consists only of white space characters..
        /// </summary>
        internal static string DestinationPathIsEmpty {
            get {
                return ResourceManager.GetString("DestinationPathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path is null..
        /// </summary>
        internal static string DestinationPathIsNull {
            get {
                return ResourceManager.GetString("DestinationPathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file access is invalid..
        /// </summary>
        internal static string InvalidFileAccess {
            get {
                return ResourceManager.GetString("InvalidFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file mode is invalid..
        /// </summary>
        internal static string InvalidFileMode {
            get {
                return ResourceManager.GetString("InvalidFileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file mode and file access combination is invalid..
        /// </summary>
        internal static string InvalidFileModeOrAccess {
            get {
                return ResourceManager.GetString("InvalidFileModeOrAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search pattern is an invalid format..
        /// </summary>
        internal static string InvalidSearchPattern {
            get {
                return ResourceManager.GetString("InvalidSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is null..
        /// </summary>
        internal static string LocationIsNull {
            get {
                return ResourceManager.GetString("LocationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is null..
        /// </summary>
        internal static string NameIsNull {
            get {
                return ResourceManager.GetString("NameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection is available to the file system..
        /// </summary>
        internal static string NoConnectionToFileSystem {
            get {
                return ResourceManager.GetString("NoConnectionToFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection is available to the specified path..
        /// </summary>
        internal static string NoConnectionToPath {
            get {
                return ResourceManager.GetString("NoConnectionToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path does not exist..
        /// </summary>
        internal static string PathDoesNotExists {
            get {
                return ResourceManager.GetString("PathDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path already exists..
        /// </summary>
        internal static string PathExists {
            get {
                return ResourceManager.GetString("PathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file system entry on the specified path is currently in use..
        /// </summary>
        internal static string PathInUse {
            get {
                return ResourceManager.GetString("PathInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is a directory..
        /// </summary>
        internal static string PathIsDirectory {
            get {
                return ResourceManager.GetString("PathIsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is empty, or consists only of white space characters..
        /// </summary>
        internal static string PathIsEmpty {
            get {
                return ResourceManager.GetString("PathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path is a file..
        /// </summary>
        internal static string PathIsFile {
            get {
                return ResourceManager.GetString("PathIsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is in an invalid format..
        /// </summary>
        internal static string PathIsInInvalidFormat {
            get {
                return ResourceManager.GetString("PathIsInInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is not supported..
        /// </summary>
        internal static string PathIsNotSupported {
            get {
                return ResourceManager.GetString("PathIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is null..
        /// </summary>
        internal static string PathIsNull {
            get {
                return ResourceManager.GetString("PathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file on path is read-only..
        /// </summary>
        internal static string PathIsReadOnly {
            get {
                return ResourceManager.GetString("PathIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path exceeds the maximum length supported by the file system..
        /// </summary>
        internal static string PathIsTooLong {
            get {
                return ResourceManager.GetString("PathIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller does not have the required permission for the path..
        /// </summary>
        internal static string PathUnauthorized {
            get {
                return ResourceManager.GetString("PathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and destination paths are equal..
        /// </summary>
        internal static string SourceAndDestinationPathEqual {
            get {
                return ResourceManager.GetString("SourceAndDestinationPathEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller does not have the required permission for either the source or the destination path..
        /// </summary>
        internal static string SourceOrDestinationPathUnauthorized {
            get {
                return ResourceManager.GetString("SourceOrDestinationPathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path is empty, or consists only of white space characters..
        /// </summary>
        internal static string SourcePathIsEmpty {
            get {
                return ResourceManager.GetString("SourcePathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path is in an invalid format..
        /// </summary>
        internal static string SourcePathIsInInvalidFormat {
            get {
                return ResourceManager.GetString("SourcePathIsInInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path is null..
        /// </summary>
        internal static string SourcePathIsNull {
            get {
                return ResourceManager.GetString("SourcePathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path does not exist..
        /// </summary>
        internal static string SourcePathNotExists {
            get {
                return ResourceManager.GetString("SourcePathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path exceeds the maximum length supported by the file system..
        /// </summary>
        internal static string SourcePathTooLong {
            get {
                return ResourceManager.GetString("SourcePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller does not have the required permission..
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI scheme is null..
        /// </summary>
        internal static string UriSchemeIsNull {
            get {
                return ResourceManager.GetString("UriSchemeIsNull", resourceCulture);
            }
        }
    }
}
